### PR TITLE
croatian translation

### PR DESCRIPTION
**Pull request by Thekuca**

### CODE REVIEW

**Comment by Gellipapa** [comment]
Until all the pages are translated, don't merge them in because then the docs will crash if you open a page that doesn't exist in that language.

**Comment by Thekuca** [comment]
> Until all the pages are translated, don't merge them in because then the docs will crash if you open a page that doesn't exist in that language.

There are all pages but not finished. I won't merge until i translate all pages.

**Review by Gellipapa — APPROVED** [review]
Hi! Is this include all pages?

**Comment by Thekuca** [comment]
> Hi! Is this include all pages?

Yes, this includes all pages but not all of them are translated yet.

**Pull request closed without merging**
